version: '3.5'
services:
    web:
        build: 
            context: .
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/app
        depends_on:  
            - redis
        env_file: .env

    redis:
        image: redis
        restart: always
        ports:
         - "${REDIS_PORT}:${REDIS_PORT}"