version: '2'
services:
    web:
        build: .
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis