pipeline {
    agent { docker { image 'python:3.7' } }
    stages {
        
        stage('Cloning Git') {
            steps {
                sh 'pwd'
                git 'https://github.com/shimaa829/DevOps-Challenges.git'      
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'pwd'
                sh 'cd DevOps-Challenges-Python-App/'
                sh 'docker-compose up --build'
              
            }
        }
    }
}